"""phase 6 investments

Revision ID: cf0671870b46
Revises: ef0755341ae9
Create Date: 2026-06-03 20:03:46.649957

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf0671870b46"
down_revision: str | None = "ef0755341ae9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investment_position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("avg_price", sa.Integer(), nullable=True),
        sa.Column("current_price", sa.Integer(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "ticker", "snapshot_date", name="uq_investment_position_snapshot"
        ),
    )
    with op.batch_alter_table("investment_position", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_investment_position_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_investment_position_snapshot_date"), ["snapshot_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("investment_position", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investment_position_snapshot_date"))
        batch_op.drop_index(batch_op.f("ix_investment_position_account_id"))

    op.drop_table("investment_position")
    # ### end Alembic commands ###
