"""phase 10: categorization rules

Revision ID: eb2e4648708c
Revises: a93f7f4fce05
Create Date: 2026-06-04 18:14:54.232626

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb2e4648708c"
down_revision: str | None = "a93f7f4fce05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rule_category_id"), ["category_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_category_id"))

    op.drop_table("rule")
    # ### end Alembic commands ###
