"""phase 21 loan documents

Phase 21 — loan attachments. One new table, ``loan_document``: metadata for files
attached to a loan (contract, schedule, payment proofs). The bytes live on disk in
the data/ volume (see expense_analyzer.attachments); this table is the index into
them. No backfill — the store starts empty. Additive, so it round-trips cleanly
via a drop on downgrade (the on-disk files, if any, are managed by the app).

Revision ID: 6562205f0771
Revises: 8639a375ba2f
Create Date: 2026-06-09 17:46:24.704791

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6562205f0771"
down_revision: str | None = "8639a375ba2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loan_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loan_id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stored_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("loan_document", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_loan_document_loan_id"), ["loan_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("loan_document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_loan_document_loan_id"))

    op.drop_table("loan_document")
    # ### end Alembic commands ###
