"""phase 8 budgets

Revision ID: 9405051fa122
Revises: cf0671870b46
Create Date: 2026-06-04 00:55:58.015928

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9405051fa122"
down_revision: str | None = "cf0671870b46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("month", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("limit_amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "month", name="uq_budget_category_month"),
    )
    with op.batch_alter_table("budget", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_budget_category_id"), ["category_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("budget", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_category_id"))

    op.drop_table("budget")
    # ### end Alembic commands ###
