"""phase 1 data model

Revision ID: a063051ff642
Revises:
Create Date: 2026-06-02 20:58:05.157431

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a063051ff642"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind", sa.Enum("expense", "income", "transfer", name="categorykind"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_batch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("active", "rolled_back", name="importstatus"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "owner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type", sa.Enum("bank", "portfolio", "cash", "loan", name="accounttype"), nullable=False
        ),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=True),
        sa.Column("booked_date", sa.Date(), nullable=False),
        sa.Column("raw_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("merchant_normalized", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("scope", sa.Enum("private", "household", name="scope"), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("import_csv", "manual", "rule", "classifier", name="txsource"),
            nullable=False,
        ),
        sa.Column("transfer_group_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transaction_account_id"), ["account_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transaction_booked_date"), ["booked_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transaction_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_transaction_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transaction_fingerprint"), ["fingerprint"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_transaction_import_batch_id"), ["import_batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transaction_transfer_group_id"), ["transfer_group_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_transfer_group_id"))
        batch_op.drop_index(batch_op.f("ix_transaction_import_batch_id"))
        batch_op.drop_index(batch_op.f("ix_transaction_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_transaction_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_transaction_category_id"))
        batch_op.drop_index(batch_op.f("ix_transaction_booked_date"))
        batch_op.drop_index(batch_op.f("ix_transaction_account_id"))

    op.drop_table("transaction")
    op.drop_table("account")
    op.drop_table("owner")
    op.drop_table("import_batch")
    op.drop_table("category")
    # ### end Alembic commands ###
