"""category color

Phase 16: optional per-category display colour ("#rrggbb"). Plain nullable add
-- no backfill (existing categories stay colourless until the owner picks one,
which renders as "no swatch"). Round-trips cleanly via drop on downgrade.

Revision ID: f97f5fe01f55
Revises: 05a13bccac8b
Create Date: 2026-06-09 13:37:37.497230

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f97f5fe01f55"
down_revision: str | None = "05a13bccac8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.add_column(sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_column("color")

    # ### end Alembic commands ###
