"""account number

Optional bank account number / IBAN on an account, for reference (copyable when
paying). Plain nullable add -- no backfill (existing accounts stay numberless
until the owner fills one in). Round-trips cleanly via drop on downgrade.

Revision ID: d3f8a1c02b47
Revises: 6562205f0771
Create Date: 2026-07-05 09:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3f8a1c02b47"
down_revision: str | None = "6562205f0771"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_column("number")

    # ### end Alembic commands ###
