"""phase 19 planned items

Phase 19a — the monthly cashflow checklist. Two new tables (``planned_item`` and
``planned_item_payment``) plus a nullable ``loan.contract_number``. No backfill:
the plan starts empty and existing loans stay without a contract number. All
additive, so it round-trips cleanly via drops on downgrade.

Revision ID: 8639a375ba2f
Revises: f97f5fe01f55
Create Date: 2026-06-09 15:52:44.046806

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8639a375ba2f"
down_revision: str | None = "f97f5fe01f55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planned_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expected_amount", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("loan_id", sa.Integer(), nullable=True),
        sa.Column("payee_account", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("due_day", sa.Integer(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("planned_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_planned_item_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_planned_item_loan_id"), ["loan_id"], unique=False)

    op.create_table(
        "planned_item_payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("planned_item_id", sa.Integer(), nullable=False),
        sa.Column("month", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["planned_item_id"],
            ["planned_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("planned_item_id", "month", name="uq_planned_item_payment_month"),
    )
    with op.batch_alter_table("planned_item_payment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_planned_item_payment_month"), ["month"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_planned_item_payment_planned_item_id"), ["planned_item_id"], unique=False
        )

    with op.batch_alter_table("loan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("contract_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("loan", schema=None) as batch_op:
        batch_op.drop_column("contract_number")

    with op.batch_alter_table("planned_item_payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_planned_item_payment_planned_item_id"))
        batch_op.drop_index(batch_op.f("ix_planned_item_payment_month"))

    op.drop_table("planned_item_payment")
    with op.batch_alter_table("planned_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_planned_item_loan_id"))
        batch_op.drop_index(batch_op.f("ix_planned_item_category_id"))

    op.drop_table("planned_item")
    # ### end Alembic commands ###
