"""add auth fields to owner

Revision ID: 4aeedacb581d
Revises: a063051ff642
Create Date: 2026-06-02 22:21:44.391035

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4aeedacb581d"
down_revision: str | None = "a063051ff642"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("owner", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f("ix_owner_username"), ["username"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("owner", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_owner_username"))
        batch_op.drop_column("is_active")
        batch_op.drop_column("password_hash")
        batch_op.drop_column("username")

    # ### end Alembic commands ###
