"""phase 5 loans

Revision ID: ef0755341ae9
Revises: 4aeedacb581d
Create Date: 2026-06-03 16:42:55.692526

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef0755341ae9"
down_revision: str | None = "4aeedacb581d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("principal", sa.Integer(), nullable=False),
        sa.Column("rate_type", sa.Enum("fixed", "variable", name="ratetype"), nullable=False),
        sa.Column("rate_bp", sa.Integer(), nullable=False),
        sa.Column("base_rate_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "installment_type",
            sa.Enum("equal", "decreasing", name="installmenttype"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("term_months", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("loan", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_loan_account_id"), ["account_id"], unique=False)

    op.create_table(
        "loan_rate_change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loan_id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("base_rate_bp", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("loan_rate_change", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_loan_rate_change_effective_date"), ["effective_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_loan_rate_change_loan_id"), ["loan_id"], unique=False)

    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("loan_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("loan_installment_index", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_transaction_loan_id"), ["loan_id"], unique=False)
        batch_op.create_foreign_key("fk_transaction_loan_id_loan", "loan", ["loan_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_constraint("fk_transaction_loan_id_loan", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_transaction_loan_id"))
        batch_op.drop_column("loan_installment_index")
        batch_op.drop_column("loan_id")

    with op.batch_alter_table("loan_rate_change", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_loan_rate_change_loan_id"))
        batch_op.drop_index(batch_op.f("ix_loan_rate_change_effective_date"))

    op.drop_table("loan_rate_change")
    with op.batch_alter_table("loan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_loan_account_id"))

    op.drop_table("loan")
    # ### end Alembic commands ###
